version: '3.9'

services:
  zenerprise-api:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile

    depends_on:
      - mongodb
    networks:
      - zenerprise-api-network

  mongodb:
    image: mongo:4.4-bionic
    restart: always
    ports:
      - 27017:27017
    volumes:
      # for persistence storage
      - mongodb-data:/data/db
    networks:
      - zenerprise-api-network

  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - zenerprise-api
    networks:
      - zenerprise-api-network

  nginx:
    restart: always
    depends_on:
      - zenerprise-api
      - client
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - zenerprise-api-network

networks:
  zenerprise-api-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
