version: '3.9'

services:
  backend:
    build:
      args:
        NODE_ENV: production
    container_name: backend_prod
    env_file: ./server/config/env/production.env
    # volumes allow sharing of data in run-time between host and container
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=production
    command: npm run start

  client:
    build:
      args:
        NODE_ENV: production
      dockerfile: Dockerfile
    container_name: frontend_prod
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=production
