version: '3.9'

services:
  backend:
    build:
      args:
        NODE_ENV: development
    container_name: backend_dev
    env_file: ./server/config/env/dev.env
    # volumes allow sharing of data in run-time between host and container
    volumes:
      # don't overwrite this folder in container with the local one
      - /app/node_modules
      # map current local directory to the /app inside the container
      #This is a must for development in order to update our container whenever a change to the source code is made. Without this, you would have to rebuild the image each time you make a change to source code.

      - ./server:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
    command: npm run dev

  client:
    build:
      args:
        NODE_ENV: development
      dockerfile: Dockerfile.dev
    container_name: frontend_dev
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
